### PR TITLE
.cpp

### PR DESCRIPTION
**Pull request by rakeshsantwani123**

### CODE REVIEW

**Comment by rakeshsantwani123** [comment]
me koi defame etc nhi kr rha khi i love u mt kr bat pr pad kr like kr de plss

**Comment by rakeshsantwani123** [comment]
me baki khi nhi kiya n kruga whtsap etc me aur kuch bhi nhi
tu git ki koi link bta rhi thi n cousre krne ki?
bs like kr de mera bda msg

**Comment by rakeshsantwani123** [comment]
mujhe yad h bhut busy h coding me bhi kr rha intren acadmy wali form bhar diya aur ab css kr rha ache kl tk ho jayega 
but tu pls ek like kr de bda mzg pad ke pls taki mere ko bhi shanti mile mujhe yad h bhut jada gussa h

**Comment by rakeshsantwani123** [comment]
sakshi whtsap pr bhi on h pr me fir bhi nhi kr rha hu msg atlest bta to de sach me move kr liya? mujhse 
kam se kam itna bta deqki galtiya ki h mene ek bar a na wha pr teri wo naxus wala pic dekh ke tera raha bhi nhi jaa rha ksm se tere binaa ek baat me ksm se drama kiye bina bol teri smile n tb tere teeth dikhte h mere hosh uda deti h i love u 
wo git wali link bta jo thi bol rhi thi n easy h 
aur tu sach me bikul sach me us pic me bhut hi jada had se jada beautiful lag rhi h raha nhi ja rha 
ese move on nhi krna n
udhar a n thodi der itni yad a rhi h me bhi tujhe copy kr rha hu jo jo intern kr rhi 
java to codewith harry se half ki h
wha pr a n yad a rhi h as a classmate hi rakh pr yad a rhi h aaja like krna fir

**Comment by rakesh0999** [comment]
crush ho gya h ab mujhe tujh pr tu mujhe classmate hi samjh pr me tere pe mrta hu bs
yad to bhut a rhi h galtiya bhi bhut ki h as a classmate hi bat rakhle bs ab me tera trust break nhi kr sakta aur qki tune mere litye bhut kuch kiya h pr bhul mt ese as classmate hi bat kr bs abse me ek bhi galti repet nhi kruga mene sb btaya muskan ko ki mere karan 4 bar fasi h wo aur family to gussa thi hi mene bhi support nhi kra ab mujhe sb samjh a gai h
last chance life me sbko milta h me to fir bhi insan hu
as a classmate hi ke le baki tujhe bhi pta h meri niyat hamesha se kesi thi aur h tere liye 
classmate to hu hi n wese hi kr le bs

**Comment by rakesh0999** [comment]
aur wo jo top h jo web aap nexus me dala h sarojni wala hi h n?
tere upar chip chij bhi expansive lagti h

**Comment by rakesh0999** [comment]
https://youtu.be/yHWPO9DDnsk

**Comment by rakesh0999** [comment]
coco thik ho gya meri git profile pr dekh ek img dala h abhi

**Comment by rakesh0999** [comment]
aur is baar mene kuch chupaya nhi ki me aacha banne ki try kiya mene kafi aache se btaya ki mere karan wo 4 bar problem me aai to usne kha ki galti aapki h bro ek to family to khtrnaak h di ki aur aap bhi unka ese trust break kiye to wo boli aapko support krna chiye hi didi ko hamesha 
aur aap ke liye wo bimar hone pr aapke liye maditation etc  aur itna sb kuch ek normal ladki nhi krti realtion me 
wo aapse bhut jada pyar krti hogi iskiye itna sb krti hogi h  aap bhi to unko return me atlest trust to do
jbki yad h didi ki family stirtct h 
usne kha didi maan jayegi qki aapke comapre me wo  jada pyar krti h madtitation etc se...
pr aapne jo unko expact tha wo nhi diya aap bhi aage bdo didi ke liye understand kro bro
maan jayegi di wo bs aapse abhi had se jada gussa h bs qki jo expact krti h whi aapne nnhi diyaa


mene har baat btai ki mene bhi bemani ki thi jo ab se nhin kruga kabhi

**Comment by rakesh0999** [comment]
apne 5.9fit ladke se itna gussa mt rakho tum kyoki jitna gussa krogi utna pyar bhi aayega

**Pull request closed without merging**
